"""
Script nạp dữ liệu mẫu (Seed Data) cho hệ thống Quản lý dự án.
Chạy bằng lệnh: python seed_data.py
"""

import sys
from datetime import datetime

from sqlalchemy import select
from sqlalchemy.orm import Session

from app.core.database import Base, SessionLocal, engine
from app.core.security import get_password_hash
from app.models import Project, TechTag, User

# Console Windows mặc định cp1252 không in được emoji / tiếng Nhật
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")


SAMPLE_PROJECTS = [
    {
        "customer_name": "株式会社みずほフィナンシャル",
        "project_name": "次世代バンキングAPI基盤構築",
        "description": "勘定系システムと外部FinTechサービスを連携するための高信頼・低遅延API Gatewayの設計および構築プロジェクト。",
        "start_date": "2025-04-01",
        "end_date": "2026-03-31",
        "is_ongoing": False,
        "team_size": 12,
        "total_man_month": 72.0,
        "source_note": "金融系プライムSIer経由での受注",
        "industry": "金融・保険",
        "outcome_note": "API応答時間を従来の30%短縮し、月間2,000万リクエストを安定処理達成。",
        "team_composition_note": "PM: 1, TechLead: 1, Backend: 6, QA: 2, DevOps: 2",
        "technologies": ["Java", "Spring Boot", "AWS", "PostgreSQL", "Docker", "Terraform"],
        "project_types": ["offshore", "new_dev"],
        "dev_process_phases": ["requirements", "design", "implementation", "testing", "release"],
    },
    {
        "customer_name": "楽天グループ株式会社",
        "project_name": "ECモール向けレコメンドエンジン刷新",
        "description": "ユーザーの閲覧履歴と購買行動を機械学習モデルでリアルタイム分析し、最適なレコメンド商品を提示するマイクロサービスの開発。",
        "start_date": "2025-06-01",
        "end_date": None,
        "is_ongoing": True,
        "team_size": 8,
        "total_man_month": 48.0,
        "source_note": "既存取引先からの追加案件",
        "industry": "Eコマース・小売り",
        "outcome_note": "CVR（購買転換率）が前年比15%向上。",
        "team_composition_note": "PM: 1, DataScientist: 2, ML Engineer: 3, Frontend: 2",
        "technologies": ["Python", "FastAPI", "Kubernetes", "Redis", "TensorFlow", "React"],
        "project_types": ["lab", "new_dev"],
        "dev_process_phases": ["design", "implementation", "testing"],
    },
    {
        "customer_name": "トヨタ自動車株式会社",
        "project_name": "コネクテッドカーテレマティクス基盤保守",
        "description": "車載通信機からリアルタイムに送信される車両運行データの蓄積・可視化ダッシュボードの機能改善および運用保守。",
        "start_date": "2024-01-01",
        "end_date": None,
        "is_ongoing": True,
        "team_size": 5,
        "total_man_month": 60.0,
        "source_note": "継続保守契約",
        "industry": "製造・自動車",
        "outcome_note": "SLA 99.99%達成、障害対応時間を平均15分に短縮。",
        "team_composition_note": "PL: 1, Backend: 2, Infrastructure: 2",
        "technologies": ["Go", "TypeScript", "AWS", "Kafka", "MySQL"],
        "project_types": ["maintenance", "ses"],
        "dev_process_phases": ["maintenance_ops"],
    },
    {
        "customer_name": "株式会社リクルート",
        "project_name": "求人マッチングAIプラットフォーム",
        "description": "求職者のスキルシートと求人要件のセマンティック検索を行い、最適なマッチングを実現するSaaS型プロダクト。",
        "start_date": "2025-02-01",
        "end_date": "2025-11-30",
        "is_ongoing": False,
        "team_size": 10,
        "total_man_month": 50.0,
        "source_note": "コンペ提案により受注",
        "industry": "人材・メディア",
        "outcome_note": "スカウト送信後の返信率が22%から38%に改善。",
        "team_composition_note": "PM: 1, Frontend: 3, Backend: 4, QA: 2",
        "technologies": ["Next.js", "TypeScript", "Python", "OpenAI API", "PostgreSQL"],
        "project_types": ["offshore", "new_dev"],
        "dev_process_phases": ["requirements", "design", "implementation", "testing", "release"],
    },
    {
        "customer_name": "エムスリー株式会社",
        "project_name": "医師向けオンライン診療支援システム",
        "description": "WebRTCを活用した医師と患者間のリアルタイムビデオ通話および電子カルテ連携システム。",
        "start_date": "2024-09-01",
        "end_date": "2025-08-31",
        "is_ongoing": False,
        "team_size": 7,
        "total_man_month": 42.0,
        "source_note": "医療ITコンソーシアム経由",
        "industry": "医療・ヘルスケア",
        "outcome_note": "全国200以上のクリニックで導入完了。",
        "team_composition_note": "PM: 1, Fullstack: 4, QA: 2",
        "technologies": ["React", "Node.js", "WebRTC", "Docker", "GCP"],
        "project_types": ["offshore", "new_dev"],
        "dev_process_phases": ["design", "implementation", "testing", "release"],
    },
    {
        "customer_name": "ヤマト運輸株式会社",
        "project_name": "配送ルート最適化アルゴリズム開発",
        "description": "交通状況、天候、荷物量からラストワンマイル配送の最短ルートを動的に計算するモバイルアプリおよびバックエンド。",
        "start_date": "2025-05-01",
        "end_date": None,
        "is_ongoing": True,
        "team_size": 6,
        "total_man_month": 36.0,
        "source_note": "物流DXイノベーション公募",
        "industry": "運輸・物流",
        "outcome_note": "ドライバーの走行距離を日平均12%削減。",
        "team_composition_note": "Lead: 1, Algorithm: 2, Mobile: 2, Backend: 1",
        "technologies": ["Flutter", "Python", "FastAPI", "PostgreSQL", "Google Maps API"],
        "project_types": ["lab", "new_dev"],
        "dev_process_phases": ["requirements", "design", "implementation"],
    },
    {
        "customer_name": "ベネッセコーポレーション",
        "project_name": "小学生向けインタラクティブ学習タブレットアプリ",
        "description": "ゲーミフィケーションを取り入れた算数・英語学習用ネイティブアプリのUI刷新と教材管理CMS開発。",
        "start_date": "2024-06-01",
        "end_date": "2025-03-31",
        "is_ongoing": False,
        "team_size": 9,
        "total_man_month": 54.0,
        "source_note": "教育系代理店からの紹介",
        "industry": "教育・EdTech",
        "outcome_note": "子供の継続学習日数が前バージョン比で40%増加。",
        "team_composition_note": "PM: 1, Unity: 3, Backend: 3, Designer: 2",
        "technologies": ["Unity", "C#", "Node.js", "Vue.js", "MySQL"],
        "project_types": ["offshore", "new_dev"],
        "dev_process_phases": ["requirements", "design", "implementation", "testing", "release"],
    },
    {
        "customer_name": "三菱地所株式会社",
        "project_name": "スマートビルIoT管理統合ポータル",
        "description": "商業ビル内の空調、照明、入退館ゲートのセンサーデータを一元集約し、省エネ自動制御を行うIoTプラットフォーム。",
        "start_date": "2025-01-15",
        "end_date": None,
        "is_ongoing": True,
        "team_size": 8,
        "total_man_month": 40.0,
        "source_note": "不動産テック案件",
        "industry": "不動産・建設",
        "outcome_note": "年間電力消費量8%削減の見込み。",
        "team_composition_note": "PM: 1, IoT: 2, Backend: 3, Frontend: 2",
        "technologies": ["Vue.js", "Python", "AWS IoT Core", "TimescaleDB", "Docker"],
        "project_types": ["lab", "new_dev"],
        "dev_process_phases": ["requirements", "design", "implementation", "testing"],
    },
    {
        "customer_name": "東京海上日動火災保険",
        "project_name": "自動車事故AI画像鑑定システム",
        "description": "事故車両の写真から損傷箇所と損傷度合いをAIが自動判別し、保険金見積もりを自動生成するシステム。",
        "start_date": "2024-10-01",
        "end_date": "2025-09-30",
        "is_ongoing": False,
        "team_size": 6,
        "total_man_month": 36.0,
        "source_note": "AIコンペ最優秀賞からの商用化",
        "industry": "金融・保険",
        "outcome_note": "査定にかかる日数を7日から1日に短縮。",
        "team_composition_note": "PM: 1, ML Engineer: 2, Backend: 2, QA: 1",
        "technologies": ["PyTorch", "Python", "FastAPI", "React", "AWS"],
        "project_types": ["offshore", "new_dev"],
        "dev_process_phases": ["requirements", "design", "implementation", "testing", "release"],
    },
    {
        "customer_name": "ソニー株式会社",
        "project_name": "エンタメ配信サービス向け課金・決済マイクロサービス",
        "description": "グローバル展開するストリーミングサービスの多通貨対応、サブスクリプション決済基盤の設計・開発。",
        "start_date": "2025-03-01",
        "end_date": None,
        "is_ongoing": True,
        "team_size": 11,
        "total_man_month": 66.0,
        "source_note": "グローバル共通プラットフォーム案件",
        "industry": "情報通信・エンタメ",
        "outcome_note": "カード決済成功率99.8%維持、チャージバック詐欺を激減。",
        "team_composition_note": "Lead: 2, Backend: 6, Security: 1, QA: 2",
        "technologies": ["Go", "gRPC", "Kubernetes", "PostgreSQL", "Stripe API"],
        "project_types": ["offshore", "new_dev"],
        "dev_process_phases": ["design", "implementation", "testing"],
    },
    {
        "customer_name": "パナソニックホールディングス",
        "project_name": "スマート家電遠隔操作モバイルアプリ開発",
        "description": "エアコン、冷蔵庫、洗濯機などのIoT家電を遠隔操作・モニタリングするiOS/Android共通アプリ。",
        "start_date": "2024-04-01",
        "end_date": "2025-01-31",
        "is_ongoing": False,
        "team_size": 8,
        "total_man_month": 48.0,
        "source_note": "家電事業部直接案件",
        "industry": "製造・電機",
        "outcome_note": "AppStoreレビュー平均4.4点達成、DL数100万突破。",
        "team_composition_note": "PM: 1, Flutter: 4, Backend: 2, UI/UX: 1",
        "technologies": ["Flutter", "Dart", "AWS", "MQTT", "Node.js"],
        "project_types": ["offshore", "new_dev"],
        "dev_process_phases": ["requirements", "design", "implementation", "testing", "release"],
    },
    {
        "customer_name": "株式会社ファーストリテイリング",
        "project_name": "店舗在庫リアルタイム追跡RFID連携システム",
        "description": "全店舗のRFIDリーダーから集約される商品棚卸・移動データを秒単位で反映する在庫同期基盤。",
        "start_date": "2025-07-01",
        "end_date": None,
        "is_ongoing": True,
        "team_size": 7,
        "total_man_month": 35.0,
        "source_note": "アパレルDX戦略案件",
        "industry": "Eコマース・小売り",
        "outcome_note": "棚卸業務時間を各店舗あたり70%削減。",
        "team_composition_note": "PL: 1, Backend: 4, Cloud: 2",
        "technologies": ["Java", "Spring Boot", "Kafka", "Redis", "MySQL"],
        "project_types": ["ses", "new_dev"],
        "dev_process_phases": ["design", "implementation"],
    },
    {
        "customer_name": "日本航空株式会社 (JAL)",
        "project_name": "フライトクルー勤務スケジューリング最適化",
        "description": "航空法規制、パイロットの保有資格、休暇希望を考慮した月次シフトスケジューリングの数理最適化システム。",
        "start_date": "2024-08-01",
        "end_date": "2025-05-31",
        "is_ongoing": False,
        "team_size": 5,
        "total_man_month": 25.0,
        "source_note": "航空運行システム刷新案件",
        "industry": "運輸・航空",
        "outcome_note": "手動シフト作成時間を月120時間から3時間に短縮。",
        "team_composition_note": "PM: 1, Optimization: 2, Frontend: 1, Backend: 1",
        "technologies": ["Python", "FastAPI", "React", "TypeScript", "Docker"],
        "project_types": ["offshore", "new_dev"],
        "dev_process_phases": ["requirements", "design", "implementation", "testing", "release"],
    },
    {
        "customer_name": "味の素株式会社",
        "project_name": "グローバルサプライチェーン需給予測ポータル",
        "description": "世界15カ国の工場・物流拠点における原材料在庫および製品需要を予測し、発注を自動推奨するシステム。",
        "start_date": "2025-02-15",
        "end_date": None,
        "is_ongoing": True,
        "team_size": 9,
        "total_man_month": 45.0,
        "source_note": "基幹システム連携プロジェクト",
        "industry": "食品・消費財",
        "outcome_note": "廃棄ロスを前年同期比で18%削減。",
        "team_composition_note": "PM: 1, Data: 3, Backend: 3, Frontend: 2",
        "technologies": ["Python", "Vue.js", "Azure", "Snowflake", "FastAPI"],
        "project_types": ["lab", "new_dev"],
        "dev_process_phases": ["requirements", "design", "implementation"],
    },
    {
        "customer_name": "ソフトバンク株式会社",
        "project_name": "5G基地局監視・自動障害復旧エージェント",
        "description": "全国の基地局ログを監視し、軽微な障害発生時にAIエージェントが自動で再起動やトラフィック迂回を実行するシステム。",
        "start_date": "2024-05-01",
        "end_date": "2025-02-28",
        "is_ongoing": False,
        "team_size": 10,
        "total_man_month": 50.0,
        "source_note": "通信ネットワーク自動化プロジェクト",
        "industry": "情報通信・インフラ",
        "outcome_note": "深夜の人的一次対応インシデント数を80%削減。",
        "team_composition_note": "PM: 1, Network: 3, Backend: 4, QA: 2",
        "technologies": ["Go", "Python", "Kubernetes", "Prometheus", "Elasticsearch"],
        "project_types": ["offshore", "new_dev"],
        "dev_process_phases": ["requirements", "design", "implementation", "testing", "release"],
    },
    {
        "customer_name": "森ビル株式会社",
        "project_name": "デジタルサイネージ広告配信CMS保守",
        "description": "都市型複合施設内の大型ビジョンおよびフロア案内サイネージへの広告スケジュール配信と稼働監視。",
        "start_date": "2024-01-01",
        "end_date": None,
        "is_ongoing": True,
        "team_size": 4,
        "total_man_month": 48.0,
        "source_note": "既存CMS長期保守案件",
        "industry": "不動産・広告",
        "outcome_note": "緊急告知テロップのリアルタイム配信機能を新規追加。",
        "team_composition_note": "Lead: 1, Frontend: 1, Backend: 1, Support: 1",
        "technologies": ["React", "Node.js", "AWS S3", "CloudFront", "PostgreSQL"],
        "project_types": ["maintenance", "ses"],
        "dev_process_phases": ["maintenance_ops"],
    },
    {
        "customer_name": "株式会社サイバーエージェント",
        "project_name": "アドテク向けリアルタイム入札(RTB)エンジン最適化",
        "description": "ミリ秒単位でオークションを行うDSP/SSPシステムのレイテンシ低減とインメモリキャッシュ最適化。",
        "start_date": "2025-04-10",
        "end_date": None,
        "is_ongoing": True,
        "team_size": 6,
        "total_man_month": 30.0,
        "source_note": "技術顧問経由での参画",
        "industry": "インターネット・広告",
        "outcome_note": "P99レイテンシを12msから7msに高速化。",
        "team_composition_note": "TechLead: 1, Rust: 3, Infrastructure: 2",
        "technologies": ["Rust", "C++", "Redis", "Kafka", "GCP"],
        "project_types": ["ses", "new_dev"],
        "dev_process_phases": ["design", "implementation", "testing"],
    },
    {
        "customer_name": "クックパッド株式会社",
        "project_name": "レシピ推薦パーソナライズ基盤リファクタリング",
        "description": "モノリス構成からマイクロサービスアーキテクチャへの段階的移行およびGraphQL Gateway導入。",
        "start_date": "2024-11-01",
        "end_date": "2025-06-30",
        "is_ongoing": False,
        "team_size": 5,
        "total_man_month": 25.0,
        "source_note": "Webサービス近代化支援",
        "industry": "インターネット・Webサービス",
        "outcome_note": "デプロイ頻度が週1回から1日複数回に向上。",
        "team_composition_note": "Lead: 1, Backend: 3, Frontend: 1",
        "technologies": ["Ruby", "TypeScript", "GraphQL", "Docker", "AWS"],
        "project_types": ["offshore", "new_dev"],
        "dev_process_phases": ["design", "implementation", "testing", "release"],
    },
    {
        "customer_name": "任天堂株式会社",
        "project_name": "ゲーム配信プラットフォーム基盤拡張",
        "description": "全世界数千万人のアクティブユーザーを支えるオンラインストアおよびセーブデータクラウド同期サービスの負荷分散基盤刷新。",
        "start_date": "2024-07-01",
        "end_date": "2025-04-30",
        "is_ongoing": False,
        "team_size": 14,
        "total_man_month": 84.0,
        "source_note": "エンターテインメント基盤公募",
        "industry": "ゲーム・エンタメ",
        "outcome_note": "新作リリース時の同時接続アクセススパイクをゼロダウンタイムで処理達成。",
        "team_composition_note": "Lead: 2, Backend: 8, Infrastructure: 3, QA: 1",
        "technologies": ["Go", "AWS", "DynamoDB", "Redis", "Docker", "Terraform"],
        "project_types": ["offshore", "new_dev"],
        "dev_process_phases": ["requirements", "design", "implementation", "testing", "release"],
    },
    {
        "customer_name": "LINEヤフー株式会社",
        "project_name": "法人向け公式アカウントCRM連携モジュール",
        "description": "LINE公式アカウントと顧客企業の既存CRMシステム（Salesforce等）をリアルタイム双方向連携するWebhook中継基盤の設計・開発。",
        "start_date": "2025-05-15",
        "end_date": None,
        "is_ongoing": True,
        "team_size": 7,
        "total_man_month": 42.0,
        "source_note": "SaaSプラットフォーム連携案件",
        "industry": "IT・通信",
        "outcome_note": "メッセージ配信遅延を平均0.5秒未満に抑え、APIスループットを3倍に強化。",
        "team_composition_note": "PM: 1, Backend: 4, Frontend: 1, DevOps: 1",
        "technologies": ["TypeScript", "Next.js", "Node.js", "Kafka", "MySQL", "Docker"],
        "project_types": ["lab", "new_dev"],
        "dev_process_phases": ["requirements", "design", "implementation", "testing"],
    },
    {
        "customer_name": "株式会社ニトリホールディングス",
        "project_name": "店舗在庫管理システム保守運用",
        "description": "全国500店舗の在庫を管理する基幹システムの保守運用。障害対応とパフォーマンス改善を継続的に実施。",
        "start_date": "2024-04-01",
        "end_date": "2026-03-31",
        "is_ongoing": False,
        "team_size": 6,
        "total_man_month": 144.0,
        "source_note": "既存保守契約の更新",
        "industry": "Eコマース・小売り",
        "outcome_note": "月間障害件数を12件から2件に削減し、夜間バッチ処理を40%高速化。",
        "team_composition_note": "PM: 1, Backend: 3, QA: 1, インフラ: 1",
        "technologies": ["Java", "Oracle", "Spring Boot", "Jenkins"],
        "project_types": ["ses", "maintenance"],
        "dev_process_phases": ["maintenance_ops", "testing"],
    },
    {
        "customer_name": "株式会社リクルートホールディングス",
        "project_name": "求人検索フロントエンド刷新",
        "description": "レガシーなjQuery実装からモダンなSPAへ全面刷新し、検索体験とページ表示速度を改善。",
        "start_date": "2025-07-01",
        "end_date": None,
        "is_ongoing": True,
        "team_size": 7,
        "total_man_month": 42.0,
        "source_note": "既存取引先からの指名発注",
        "industry": "人材・メディア",
        "outcome_note": "初期表示速度を2.8秒から0.9秒へ短縮、検索離脱率を18%改善。",
        "team_composition_note": "PM: 1, TechLead: 1, Frontend: 4, QA: 1",
        "technologies": ["JavaScript", "React", "TypeScript", "Vite", "GraphQL"],
        "project_types": ["offshore", "new_dev"],
        "dev_process_phases": ["design", "implementation", "testing", "release"],
    },
    {
        "customer_name": "日本生命保険相互会社",
        "project_name": "保険契約者向けポータル改修",
        "description": "契約内容照会と各種変更手続きをオンライン化する契約者ポータルの機能追加および改修。",
        "start_date": "2025-01-06",
        "end_date": "2025-12-26",
        "is_ongoing": False,
        "team_size": 10,
        "total_man_month": 96.0,
        "source_note": "金融系SIerからの二次請け",
        "industry": "金融・保険",
        "outcome_note": "紙手続きの比率を65%から22%へ削減、コールセンター問い合わせを月3割減。",
        "team_composition_note": "PM: 1, BrSE: 1, Backend: 4, Frontend: 3, QA: 1",
        "technologies": ["Java", "Spring Boot", "Angular", "Oracle", "Azure"],
        "project_types": ["offshore", "maintenance"],
        "dev_process_phases": ["requirements", "design", "implementation", "testing", "release"],
    },
    {
        "customer_name": "株式会社エイチ・アイ・エス",
        "project_name": "旅行予約エンジン性能改善",
        "description": "繁忙期のアクセス集中で頻発していたタイムアウトを解消するため、予約エンジンの全面チューニングを実施。",
        "start_date": "2025-03-03",
        "end_date": "2025-09-30",
        "is_ongoing": False,
        "team_size": 5,
        "total_man_month": 35.0,
        "source_note": "パフォーマンス課題の相談から受注",
        "industry": "運輸・航空",
        "outcome_note": "ピーク時応答時間を6.2秒から1.1秒へ短縮、タイムアウト発生をゼロ化。",
        "team_composition_note": "TechLead: 1, Backend: 3, DBA: 1",
        "technologies": ["PHP", "Laravel", "MySQL", "Redis", "AWS"],
        "project_types": ["ses", "maintenance"],
        "dev_process_phases": ["design", "implementation", "testing", "maintenance_ops"],
    },
    {
        "customer_name": "サントリーホールディングス株式会社",
        "project_name": "自販機IoTデータ基盤構築",
        "description": "全国の自動販売機から売上と在庫データを収集し、補充計画を最適化するデータ基盤の新規構築。",
        "start_date": "2025-05-12",
        "end_date": None,
        "is_ongoing": True,
        "team_size": 9,
        "total_man_month": 63.0,
        "source_note": "DX推進部門からの直接発注",
        "industry": "食品・消費財",
        "outcome_note": "補充ルート最適化により配送コストを年間12%削減見込み。",
        "team_composition_note": "PM: 1, DataEngineer: 3, Backend: 3, DevOps: 2",
        "technologies": ["Python", "FastAPI", "Kafka", "Snowflake", "Terraform", "AWS"],
        "project_types": ["lab", "new_dev"],
        "dev_process_phases": ["requirements", "design", "implementation"],
    },
    {
        "customer_name": "株式会社ファーストリテイリング",
        "project_name": "店舗スタッフ向けモバイルアプリ開発",
        "description": "店舗スタッフがシフト確認と在庫照会を行うためのクロスプラットフォームモバイルアプリを新規開発。",
        "start_date": "2025-02-10",
        "end_date": "2026-01-30",
        "is_ongoing": False,
        "team_size": 8,
        "total_man_month": 72.0,
        "source_note": "社内公募コンペを経て受注",
        "industry": "Eコマース・小売り",
        "outcome_note": "シフト確認の所要時間を平均5分から30秒へ短縮、利用率92%を達成。",
        "team_composition_note": "PM: 1, Mobile: 4, Backend: 2, QA: 1",
        "technologies": ["Kotlin", "Swift", "Flutter", "Firebase", "Node.js"],
        "project_types": ["offshore", "new_dev"],
        "dev_process_phases": ["requirements", "design", "implementation", "testing", "release"],
    },
    {
        "customer_name": "東京海上日動火災保険株式会社",
        "project_name": "損害査定ワークフロー自動化",
        "description": "事故受付から損害査定までの社内ワークフローを自動化し、書類処理をデジタル化するシステムの構築。",
        "start_date": "2024-10-01",
        "end_date": "2025-11-28",
        "is_ongoing": False,
        "team_size": 11,
        "total_man_month": 121.0,
        "source_note": "既存顧客からのリプレース案件",
        "industry": "金融・保険",
        "outcome_note": "査定完了までの平均日数を9日から3日へ短縮。",
        "team_composition_note": "PM: 1, BrSE: 1, Backend: 5, Frontend: 2, QA: 2",
        "technologies": ["C#", ".NET", "Azure", "SQL Server", "Power Automate"],
        "project_types": ["offshore", "new_dev"],
        "dev_process_phases": ["requirements", "design", "implementation", "testing", "release"],
    },
    {
        "customer_name": "株式会社NTTデータ",
        "project_name": "官公庁向け申請システム保守",
        "description": "電子申請システムの年度改正対応と障害一次対応を担当する常駐保守案件。",
        "start_date": "2025-04-01",
        "end_date": None,
        "is_ongoing": True,
        "team_size": 4,
        "total_man_month": 48.0,
        "source_note": "長期常駐契約",
        "industry": "情報通信・インフラ",
        "outcome_note": "年度改正リリースを無停止で完了、SLA達成率100%を維持。",
        "team_composition_note": "リーダー: 1, Backend: 2, QA: 1",
        "technologies": ["Java", "Spring Boot", "PostgreSQL", "Kubernetes"],
        "project_types": ["ses", "maintenance"],
        "dev_process_phases": ["maintenance_ops", "release"],
    },
    {
        "customer_name": "freee株式会社",
        "project_name": "会計SaaS請求モジュール拡張",
        "description": "インボイス制度対応に伴う請求書発行モジュールの仕様追加と既存データの移行対応。",
        "start_date": "2025-06-02",
        "end_date": "2026-02-27",
        "is_ongoing": False,
        "team_size": 6,
        "total_man_month": 54.0,
        "source_note": "プロダクト開発チームの増員要請",
        "industry": "金融・保険",
        "outcome_note": "インボイス対応を法改正期日の2か月前に完了、移行エラー率0.02%。",
        "team_composition_note": "TechLead: 1, Backend: 4, QA: 1",
        "technologies": ["Ruby", "Ruby on Rails", "PostgreSQL", "Docker", "AWS"],
        "project_types": ["ses", "maintenance"],
        "dev_process_phases": ["requirements", "implementation", "testing", "release"],
    },
    {
        "customer_name": "株式会社ディー・エヌ・エー",
        "project_name": "ライブ配信基盤スケール改善",
        "description": "同時接続数の急増に耐えるため、ライブ配信基盤のアーキテクチャを見直し水平スケール対応を実施。",
        "start_date": "2025-08-01",
        "end_date": None,
        "is_ongoing": True,
        "team_size": 7,
        "total_man_month": 49.0,
        "source_note": "技術顧問からの紹介",
        "industry": "ゲーム・エンタメ",
        "outcome_note": "同時接続上限を5万から30万へ拡張、配信遅延を平均1.2秒に維持。",
        "team_composition_note": "TechLead: 1, Backend: 4, SRE: 2",
        "technologies": ["Go", "gRPC", "Redis", "Kubernetes", "WebRTC", "Prometheus"],
        "project_types": ["lab", "maintenance"],
        "dev_process_phases": ["design", "implementation", "maintenance_ops"],
    },
    {
        "customer_name": "パナソニック株式会社",
        "project_name": "工場設備予知保全システム",
        "description": "製造ラインのセンサーデータから故障予兆を検知し、計画外停止を防ぐ予知保全システムの開発。",
        "start_date": "2025-01-20",
        "end_date": "2026-01-16",
        "is_ongoing": False,
        "team_size": 10,
        "total_man_month": 110.0,
        "source_note": "研究開発部門との共同プロジェクト",
        "industry": "製造・電機",
        "outcome_note": "計画外停止を年間38%削減、保全コストを年6,000万円削減。",
        "team_composition_note": "PM: 1, DataScientist: 2, ML: 2, Backend: 3, DevOps: 2",
        "technologies": ["Python", "PyTorch", "MQTT", "TimescaleDB", "Docker", "Grafana"],
        "project_types": ["lab", "new_dev"],
        "dev_process_phases": ["requirements", "design", "implementation", "testing"],
    },
    {
        "customer_name": "株式会社カカクコム",
        "project_name": "価格比較サイト検索基盤移行",
        "description": "全文検索エンジンを自社運用からマネージドサービスへ移行し、検索精度と運用負荷を改善。",
        "start_date": "2025-03-17",
        "end_date": "2025-10-31",
        "is_ongoing": False,
        "team_size": 5,
        "total_man_month": 37.5,
        "source_note": "インフラ刷新のRFP経由",
        "industry": "インターネット・Webサービス",
        "outcome_note": "検索レイテンシを45%改善、インフラ運用工数を月80時間削減。",
        "team_composition_note": "TechLead: 1, Backend: 3, SRE: 1",
        "technologies": ["Elasticsearch", "Python", "Django", "AWS", "Terraform"],
        "project_types": ["offshore", "maintenance"],
        "dev_process_phases": ["design", "implementation", "testing", "release", "maintenance_ops"],
    },
    {
        "customer_name": "株式会社マネーフォワード",
        "project_name": "家計簿アプリ連携API拡充",
        "description": "金融機関との口座連携APIを拡充し、対応金融機関数を拡大するとともに同期失敗率を低減。",
        "start_date": "2025-05-07",
        "end_date": None,
        "is_ongoing": True,
        "team_size": 6,
        "total_man_month": 36.0,
        "source_note": "プロダクトロードマップに基づく発注",
        "industry": "金融・保険",
        "outcome_note": "対応金融機関を210行から340行へ拡大、同期失敗率を7%から1.5%へ低減。",
        "team_composition_note": "TechLead: 1, Backend: 4, QA: 1",
        "technologies": ["Go", "PostgreSQL", "Redis", "Kubernetes", "gRPC"],
        "project_types": ["ses", "new_dev"],
        "dev_process_phases": ["design", "implementation", "testing"],
    },
    {
        "customer_name": "学校法人早稲田大学",
        "project_name": "オンライン授業配信プラットフォーム",
        "description": "オンデマンドとライブの両方式に対応した授業配信プラットフォームを新規構築し、出席管理と連携。",
        "start_date": "2024-09-02",
        "end_date": "2025-08-29",
        "is_ongoing": False,
        "team_size": 9,
        "total_man_month": 99.0,
        "source_note": "公募入札で落札",
        "industry": "教育・EdTech",
        "outcome_note": "同時受講2万人を安定配信、出席管理の手作業を完全撤廃。",
        "team_composition_note": "PM: 1, Backend: 4, Frontend: 2, インフラ: 2",
        "technologies": ["TypeScript", "Nest.js", "React", "WebRTC", "GCP", "PostgreSQL"],
        "project_types": ["offshore", "new_dev"],
        "dev_process_phases": ["requirements", "design", "implementation", "testing", "release"],
    },
    {
        "customer_name": "ヤマト運輸株式会社",
        "project_name": "配送ドライバー向け経路最適化",
        "description": "当日配送のドライバー向けに交通状況を加味した配送順を自動生成する経路最適化エンジンを開発。",
        "start_date": "2025-04-14",
        "end_date": None,
        "is_ongoing": True,
        "team_size": 8,
        "total_man_month": 56.0,
        "source_note": "物流DXコンペ経由",
        "industry": "運輸・物流",
        "outcome_note": "1日あたり走行距離を平均11%短縮、再配達率を4ポイント改善。",
        "team_composition_note": "PM: 1, アルゴリズム: 2, Backend: 3, Mobile: 2",
        "technologies": ["Python", "FastAPI", "Google Maps API", "PostgreSQL", "Docker"],
        "project_types": ["lab", "new_dev"],
        "dev_process_phases": ["requirements", "design", "implementation"],
    },
    {
        "customer_name": "株式会社ベネッセコーポレーション",
        "project_name": "学習教材コンテンツ管理システム",
        "description": "教材コンテンツの入稿、校正、公開までを一元管理するCMSを構築し、編集フローを効率化。",
        "start_date": "2024-11-05",
        "end_date": "2025-10-31",
        "is_ongoing": False,
        "team_size": 7,
        "total_man_month": 84.0,
        "source_note": "既存システムのリプレース相談",
        "industry": "教育・EdTech",
        "outcome_note": "教材公開までのリードタイムを14日から4日へ短縮。",
        "team_composition_note": "PM: 1, Backend: 3, Frontend: 2, QA: 1",
        "technologies": ["PHP", "Laravel", "Vue.js", "MySQL", "AWS S3"],
        "project_types": ["offshore", "new_dev"],
        "dev_process_phases": ["requirements", "design", "implementation", "testing", "release"],
    },
    {
        "customer_name": "株式会社ソラコム",
        "project_name": "IoT SIM管理コンソール改修",
        "description": "数十万回線規模のSIMを扱う管理コンソールの一覧表示と一括操作機能を改修し、操作性を改善。",
        "start_date": "2025-02-03",
        "end_date": "2025-08-29",
        "is_ongoing": False,
        "team_size": 5,
        "total_man_month": 35.0,
        "source_note": "開発チームの増員要請",
        "industry": "IT・通信",
        "outcome_note": "10万件一覧の表示を12秒から1.5秒へ改善、一括操作の失敗率を0.1%未満に。",
        "team_composition_note": "TechLead: 1, Frontend: 2, Backend: 2",
        "technologies": ["TypeScript", "React", "Node.js", "DynamoDB", "AWS"],
        "project_types": ["ses", "maintenance"],
        "dev_process_phases": ["design", "implementation", "testing", "maintenance_ops"],
    },
    {
        "customer_name": "大和ハウス工業株式会社",
        "project_name": "住宅設備点検アプリ開発",
        "description": "現場作業員がタブレットで点検結果を記録し、写真付きレポートを自動生成するアプリを開発。",
        "start_date": "2025-06-16",
        "end_date": None,
        "is_ongoing": True,
        "team_size": 6,
        "total_man_month": 30.0,
        "source_note": "現場DX推進の一環として発注",
        "industry": "不動産・建設",
        "outcome_note": "点検レポート作成時間を1件あたり40分から8分へ短縮。",
        "team_composition_note": "PM: 1, Mobile: 3, Backend: 2",
        "technologies": ["Dart", "Flutter", "Firebase", "Python", "FastAPI"],
        "project_types": ["offshore", "new_dev"],
        "dev_process_phases": ["design", "implementation", "testing"],
    },
    {
        "customer_name": "株式会社ぐるなび",
        "project_name": "飲食店予約基盤のレガシー移行",
        "description": "オンプレミスで稼働していた予約基盤をクラウドへ移行し、段階的にマイクロサービス化を推進。",
        "start_date": "2024-07-01",
        "end_date": "2026-03-31",
        "is_ongoing": False,
        "team_size": 12,
        "total_man_month": 180.0,
        "source_note": "長期パートナー契約",
        "industry": "Eコマース・小売り",
        "outcome_note": "インフラ費用を年間28%削減、デプロイ頻度を月1回から週3回へ向上。",
        "team_composition_note": "PM: 1, アーキテクト: 1, Backend: 6, SRE: 3, QA: 1",
        "technologies": ["Java", "Spring Boot", "Kubernetes", "Kafka", "MySQL", "Terraform"],
        "project_types": ["offshore", "maintenance"],
        "dev_process_phases": ["requirements", "design", "implementation", "testing", "release", "maintenance_ops"],
    },
    {
        "customer_name": "株式会社サイバーエージェント",
        "project_name": "広告配信レポート基盤刷新",
        "description": "広告主向けレポート画面の集計処理を見直し、大量データでも即時に結果を返せる基盤へ刷新。",
        "start_date": "2025-09-01",
        "end_date": None,
        "is_ongoing": True,
        "team_size": 7,
        "total_man_month": 35.0,
        "source_note": "既存取引先からの追加発注",
        "industry": "インターネット・広告",
        "outcome_note": "レポート生成を平均24秒から2秒へ短縮、日次バッチを廃止。",
        "team_composition_note": "TechLead: 1, Backend: 4, DataEngineer: 2",
        "technologies": ["Go", "ClickHouse", "Kafka", "Kubernetes", "Grafana"],
        "project_types": ["lab", "new_dev"],
        "dev_process_phases": ["design", "implementation", "testing"],
    },
    {
        "customer_name": "オムロン株式会社",
        "project_name": "制御機器ファームウェア検証自動化",
        "description": "制御機器のファームウェア検証をハードウェアインザループで自動化し、リリース前検証を短縮。",
        "start_date": "2025-01-14",
        "end_date": "2025-12-19",
        "is_ongoing": False,
        "team_size": 6,
        "total_man_month": 66.0,
        "source_note": "品質保証部門からの直接依頼",
        "industry": "製造・電機",
        "outcome_note": "検証工数を1リリースあたり200時間から45時間へ削減。",
        "team_composition_note": "TechLead: 1, 組込: 3, QA自動化: 2",
        "technologies": ["C++", "Python", "Jenkins", "Docker"],
        "project_types": ["ses", "maintenance"],
        "dev_process_phases": ["design", "implementation", "testing", "maintenance_ops"],
    },
    {
        "customer_name": "株式会社メドレー",
        "project_name": "オンライン診療予約システム改修",
        "description": "オンライン診療の予約導線を見直し、医療機関ごとの複雑な予約ルールに対応できるよう改修。",
        "start_date": "2025-04-07",
        "end_date": "2026-02-27",
        "is_ongoing": False,
        "team_size": 8,
        "total_man_month": 80.0,
        "source_note": "医療DX領域での継続案件",
        "industry": "医療・ヘルスケア",
        "outcome_note": "予約完了率を61%から84%へ改善、予約起因の問い合わせを半減。",
        "team_composition_note": "PM: 1, Backend: 3, Frontend: 3, QA: 1",
        "technologies": ["TypeScript", "Next.js", "Node.js", "PostgreSQL", "AWS"],
        "project_types": ["offshore", "maintenance"],
        "dev_process_phases": ["requirements", "design", "implementation", "testing", "release"],
    },
    {
        "customer_name": "株式会社ZOZO",
        "project_name": "サイズレコメンド精度改善",
        "description": "購入履歴と返品理由を学習し、ユーザーごとに最適なサイズを提案するモデルの精度改善。",
        "start_date": "2025-07-14",
        "end_date": None,
        "is_ongoing": True,
        "team_size": 5,
        "total_man_month": 25.0,
        "source_note": "機械学習領域での技術支援",
        "industry": "Eコマース・小売り",
        "outcome_note": "サイズ起因の返品率を9.2%から6.1%へ低減。",
        "team_composition_note": "DataScientist: 2, ML: 2, Backend: 1",
        "technologies": ["Python", "PyTorch", "FastAPI", "Snowflake", "Docker"],
        "project_types": ["lab", "maintenance"],
        "dev_process_phases": ["implementation", "testing", "maintenance_ops"],
    },
    {
        "customer_name": "株式会社エムスリー",
        "project_name": "医師向け情報配信基盤構築",
        "description": "医師の専門領域に応じて最適な医療情報を配信するパーソナライズ基盤を新規構築。",
        "start_date": "2024-10-15",
        "end_date": "2025-09-30",
        "is_ongoing": False,
        "team_size": 9,
        "total_man_month": 99.0,
        "source_note": "新規顧客の公募案件",
        "industry": "医療・ヘルスケア",
        "outcome_note": "配信コンテンツの開封率を22%から41%へ向上。",
        "team_composition_note": "PM: 1, Backend: 4, DataEngineer: 2, Frontend: 2",
        "technologies": ["Scala", "Kafka", "Elasticsearch", "React", "GCP"],
        "project_types": ["offshore", "new_dev"],
        "dev_process_phases": ["requirements", "design", "implementation", "testing", "release"],
    },
    {
        "customer_name": "株式会社バンダイナムコエンターテインメント",
        "project_name": "モバイルゲーム運用基盤保守",
        "description": "運用中タイトルのイベント実装とサーバー安定化を担当する継続保守案件。",
        "start_date": "2025-04-01",
        "end_date": None,
        "is_ongoing": True,
        "team_size": 5,
        "total_man_month": 60.0,
        "source_note": "運用フェーズからの参画",
        "industry": "ゲーム・エンタメ",
        "outcome_note": "イベント開始直後の障害をゼロ化、サーバーコストを月18%削減。",
        "team_composition_note": "リーダー: 1, Backend: 3, インフラ: 1",
        "technologies": ["C#", "Unity", "Redis", "MySQL", "AWS"],
        "project_types": ["ses", "maintenance"],
        "dev_process_phases": ["implementation", "release", "maintenance_ops"],
    },
    {
        "customer_name": "三井不動産株式会社",
        "project_name": "商業施設来訪分析ダッシュボード",
        "description": "館内のWi-Fiとカメラから取得した来訪データを可視化し、テナント配置の検討を支援するダッシュボード。",
        "start_date": "2025-03-10",
        "end_date": "2025-11-28",
        "is_ongoing": False,
        "team_size": 6,
        "total_man_month": 48.0,
        "source_note": "施設運営部門からの相談",
        "industry": "不動産・建設",
        "outcome_note": "テナント別来訪分析を月次から日次へ、施策判断のリードタイムを1/4に短縮。",
        "team_composition_note": "PM: 1, DataEngineer: 2, Frontend: 2, Backend: 1",
        "technologies": ["Python", "Django", "React", "PostgreSQL", "Azure"],
        "project_types": ["lab", "new_dev"],
        "dev_process_phases": ["requirements", "design", "implementation", "release"],
    },
    {
        "customer_name": "KDDI株式会社",
        "project_name": "回線契約管理システム年度対応",
        "description": "料金プラン改定に伴う契約管理システムの改修と、旧プランからの移行バッチの開発。",
        "start_date": "2025-05-19",
        "end_date": "2026-03-13",
        "is_ongoing": False,
        "team_size": 10,
        "total_man_month": 100.0,
        "source_note": "通信キャリア向け長期契約",
        "industry": "情報通信・インフラ",
        "outcome_note": "300万契約の移行をダウンタイム30分で完了、移行差異ゼロ。",
        "team_composition_note": "PM: 1, BrSE: 1, Backend: 5, QA: 3",
        "technologies": ["Java", "Oracle", "Spring Boot", "Jenkins", "Kubernetes"],
        "project_types": ["ses", "maintenance"],
        "dev_process_phases": ["requirements", "implementation", "testing", "release", "maintenance_ops"],
    },
    {
        "customer_name": "株式会社SmartHR",
        "project_name": "人事労務SaaS権限管理刷新",
        "description": "企業規模の拡大に対応するため、細粒度の権限設定を可能にする権限管理機構へ刷新。",
        "start_date": "2025-08-18",
        "end_date": None,
        "is_ongoing": True,
        "team_size": 6,
        "total_man_month": 30.0,
        "source_note": "プロダクトチームへの技術支援",
        "industry": "IT・通信",
        "outcome_note": "権限設定に関する問い合わせを月62件から11件へ削減。",
        "team_composition_note": "TechLead: 1, Backend: 4, QA: 1",
        "technologies": ["Ruby", "Ruby on Rails", "PostgreSQL", "Redis", "AWS"],
        "project_types": ["ses", "new_dev"],
        "dev_process_phases": ["design", "implementation", "testing"],
    },
    {
        "customer_name": "ソフトバンク株式会社",
        "project_name": "社内問い合わせチャットボット",
        "description": "社内規程や手続きに関する問い合わせへ自動応答する生成AIチャットボットを構築。",
        "start_date": "2025-06-09",
        "end_date": "2026-03-31",
        "is_ongoing": False,
        "team_size": 7,
        "total_man_month": 63.0,
        "source_note": "社内DX部門のPoCから本開発へ移行",
        "industry": "情報通信・インフラ",
        "outcome_note": "総務部門への問い合わせを月1,800件から520件へ削減。",
        "team_composition_note": "PM: 1, ML: 2, Backend: 3, Frontend: 1",
        "technologies": ["Python", "FastAPI", "OpenAI API", "Elasticsearch", "Azure"],
        "project_types": ["lab", "new_dev"],
        "dev_process_phases": ["requirements", "design", "implementation", "testing", "release"],
    },
    {
        "customer_name": "株式会社島津製作所",
        "project_name": "分析装置データ管理システム改修",
        "description": "分析装置から出力される測定データを一元管理し、法規制対応の監査証跡を保持する仕組みへ改修。",
        "start_date": "2024-12-02",
        "end_date": "2025-11-28",
        "is_ongoing": False,
        "team_size": 8,
        "total_man_month": 88.0,
        "source_note": "規制対応要件からの引き合い",
        "industry": "製造・電機",
        "outcome_note": "監査対応の資料準備工数を1回あたり120時間から20時間へ削減。",
        "team_composition_note": "PM: 1, Backend: 4, QA: 2, 品質保証: 1",
        "technologies": ["C#", ".NET", "SQL Server", "Docker", "Azure"],
        "project_types": ["offshore", "maintenance"],
        "dev_process_phases": ["requirements", "design", "implementation", "testing", "maintenance_ops"],
    },
    {
        "customer_name": "株式会社スタディスト",
        "project_name": "マニュアル作成ツール検索改善",
        "description": "社内マニュアルの全文検索を刷新し、画像内テキストも検索対象に含める機能を追加。",
        "start_date": "2025-09-16",
        "end_date": None,
        "is_ongoing": True,
        "team_size": 4,
        "total_man_month": 16.0,
        "source_note": "検索機能の課題相談から受注",
        "industry": "教育・EdTech",
        "outcome_note": "検索ヒット率を54%から88%へ改善、目的のマニュアル到達時間を半減。",
        "team_composition_note": "TechLead: 1, Backend: 2, Frontend: 1",
        "technologies": ["JavaScript", "Vue.js", "Node.js", "Elasticsearch", "GCP"],
        "project_types": ["ses", "new_dev"],
        "dev_process_phases": ["design", "implementation", "testing"],
    },
]


def seed():
    Base.metadata.create_all(bind=engine)
    db: Session = SessionLocal()

    try:
        print("🌱 Seeding data...")

        # 1. Tạo user demo mẫu nếu chưa có (chuẩn role member)
        default_users = [
            {"email": "admin@gmail.com", "password": "AdminPass123@", "role": "member"},
            {"email": "admin@example.com", "password": "Password123", "role": "member"},
        ]
        for u in default_users:
            user = db.scalar(select(User).where(User.email == u["email"]))
            if not user:
                user = User(
                    email=u["email"],
                    password_hash=get_password_hash(u["password"]),
                    role=u["role"],
                )
                db.add(user)
                db.commit()
                print(f"  ✓ Created user: {u['email']} (Password: {u['password']}, Role: member)")
            else:
                # Cập nhật lại mật khẩu và role chuẩn member
                user.password_hash = get_password_hash(u["password"])
                user.role = u["role"]
                db.commit()
                print(f"  ✓ Updated user password & role: {u['email']}")

        admin_email = "admin@gmail.com"

        # 2. Xử lý TechTag và nạp Projects
        all_tags = set()
        for p in SAMPLE_PROJECTS:
            for tag in p["technologies"]:
                all_tags.add(tag.strip())

        # Thêm các tag mới vào DB
        existing_tags = set(db.scalars(select(TechTag.name)).all())
        new_tags = all_tags - existing_tags
        for tag_name in new_tags:
            db.add(TechTag(name=tag_name))
        db.commit()
        print(f"  ✓ Synchronized {len(all_tags)} unique tech tags (added {len(new_tags)} new tags)")

        # 3. Nạp Projects
        added_count = 0
        for p_data in SAMPLE_PROJECTS:
            # Kiểm tra xem dự án đã tồn tại chưa (tránh nạp trùng khi chạy nhiều lần)
            exists = db.scalar(
                select(Project).where(
                    Project.customer_name == p_data["customer_name"],
                    Project.project_name == p_data["project_name"],
                    Project.deleted_at.is_(None),
                )
            )
            if exists:
                continue

            project = Project(
                customer_name=p_data["customer_name"],
                project_name=p_data["project_name"],
                description=p_data["description"],
                start_date=p_data["start_date"],
                end_date=p_data["end_date"],
                is_ongoing=p_data["is_ongoing"],
                team_size=p_data["team_size"],
                total_man_month=p_data["total_man_month"],
                source_note=p_data["source_note"],
                industry=p_data["industry"],
                outcome_note=p_data["outcome_note"],
                team_composition_note=p_data["team_composition_note"],
                technologies_csv=",".join(p_data["technologies"]),
                project_types_csv=",".join(p_data["project_types"]),
                dev_process_phases_csv=",".join(p_data["dev_process_phases"]),
                created_by=admin_email,
            )
            db.add(project)
            added_count += 1

        db.commit()
        print(f"  ✓ Added {added_count} projects into database.")
        print("🎉 Seed data completed successfully!")

    except Exception as e:
        db.rollback()
        print(f"❌ Error while seeding data: {e}")
        raise e
    finally:
        db.close()


if __name__ == "__main__":
    seed()